const orderStatusTranslations = {
    "AWAIT_PAYMENT": "ĐANG CHỜ THANH TOÁN 💳",
    "AWAIT_ACCEPT": "ĐANG CHỜ XÁC NHẬN ⏳",
    "PREPARING": "ĐANG CHUẨN BỊ - GÓI HÀNG 📦",
    "TRANSPORTING": "ĐANG VẬN CHUYỂN 🚚",
    "AWAIT_RATING": "ĐANG CHỜ ĐÁNH GIÁ 🌟",
    "COMPLETE": "ĐÃ HOÀN THÀNH ✅",
    "CANCELED": "ĐÃ HỦY ❌",
};
const genreGroupTranslations = {
    "EDUCATIONS": "GIÁO DỤC",
    "OTHERS": "KHÁC",
    "TEXTBOOKS": "SÁCH GIÁO KHOA - THAM KHẢO",
    "ECONOMICS": "KINH TẾ",
    "SPYCHOLOGIES": "TÂM LÝ & KỸ NĂNG SỐNG",
    "LANGUAGES": "NGOẠI NGỮ",
    "CHILDRENS": "SÁCH THIẾU NHI",
    "BIOGRAPHIES": "TIỂU SỬ & HỒI KÝ",
    "LITERATURES": "VĂN HỌC"
};
const genreTranslations = {
    "PARENTING_GUIDES": "Hướng dẫn nuôi dạy con cái",
    "CHILD_DEVELOPMENT": "Phát triển trẻ em",
    "POSITIVE_PARENTING": "Nuôi dạy con cái tích cực",
    "DISCIPLINE": "Kỷ luật",
    "PARENTING_STYLES": "Các kiểu nuôi dạy con cái",
    "SINGLE_PARENTING": "Nuôi dạy con cái đơn thân",
    "WORK_LIFE_BALANCE": "Cân bằng công việc và cuộc sống",
    "PARENTING_CHALLENGES": "Thách thức trong nuôi dạy con cái",
    "SPECIAL_NEEDS": "Những nhu cầu đặc biệt",
    "FAMILY_RELATIONSHIPS": "Mối quan hệ gia đình",
    "PARENTING_TIPS": "Mẹo nuôi dạy con cái",
    // Add other translations here
    "COOKING": "Nấu ăn",
    "TRAVEL": "Du lịch",
    "HEALTH": "Sức khỏe",
    "ART": "Nghệ thuật",
    "MUSIC": "Âm nhạc",
    "RELIGION": "Tôn giáo",
    "SPIRITUALITY": "Tâm linh",
    "SCIENCE": "Khoa học",
    "PHILOSOPHY": "Triết học",
    "BUSINESS": "Kinh doanh",
    "EDUCATION": "Giáo dục",
    "GRAPHIC_NOVEL": "Tiểu thuyết đồ họa",
    "SPORTS": "Thể thao",
    "TECHNOLOGY": "Công nghệ",
    "TEXTBOOK": "Sách giáo khoa",
    "REFERENCE_BOOK": "Sách tham khảo",
    "WORKBOOK": "Sách bài tập",
    "GUIDE": "Hướng dẫn",
    "HANDBOOK": "Sổ tay",
    "ENCYCLOPEDIA": "Từ điển bách khoa",
    "ATLAS": "Bản đồ",
    "DICTIONARY": "Từ điển",
    "MANUAL": "Sách hướng dẫn",
    "TEXTBOOK_SERIES": "Chuỗi sách giáo khoa",
    "MICROECONOMICS": "Kinh tế vi mô",
    "MACROECONOMICS": "Kinh tế vĩ mô",
    "ECONOMIC_THEORY": "Lý thuyết kinh tế",
    "DEVELOPMENT_ECONOMICS": "Kinh tế phát triển",
    "INTERNATIONAL_ECONOMICS": "Kinh tế quốc tế",
    "BEHAVIORAL_ECONOMICS": "Kinh tế hành vi",
    "PUBLIC_ECONOMICS": "Kinh tế công",
    "ENVIRONMENTAL_ECONOMICS": "Kinh tế môi trường",
    "ECONOMETRICS": "Kinh tế lượng",
    "LABOR_ECONOMICS": "Kinh tế lao động",
    "FINANCIAL_ECONOMICS": "Kinh tế tài chính",
    "HEALTH_ECONOMICS": "Kinh tế y tế",
    "INDUSTRIAL_ORGANIZATION": "Tổ chức công nghiệp",
    "SELF_HELP": "Tự trợ giúp",
    "PERSONAL_DEVELOPMENT": "Phát triển cá nhân",
    "EMOTIONAL_INTELLIGENCE": "Trí tuệ cảm xúc",
    "MINDFULNESS": "Chánh niệm",
    "STRESS_MANAGEMENT": "Quản lý căng thẳng",
    "TIME_MANAGEMENT": "Quản lý thời gian",
    "COMMUNICATION_SKILLS": "Kỹ năng giao tiếp",
    "CONFLICT_RESOLUTION": "Giải quyết xung đột",
    "MOTIVATION": "Động lực",
    "LEADERSHIP": "Lãnh đạo",
    "RESILIENCE": "Khả năng phục hồi",
    "DECISION_MAKING": "Ra quyết định",
    "RELATIONSHIP_BUILDING": "Xây dựng mối quan hệ",
    "SELF_AWARENESS": "Nhận thức bản thân",
    "LANGUAGE_TEXTBOOK": "Sách giáo khoa ngôn ngữ",
    "GRAMMAR_GUIDE": "Hướng dẫn ngữ pháp",
    "VOCABULARY_BOOK": "Sách từ vựng",
    "LANGUAGE_WORKBOOK": "Sách bài tập ngôn ngữ",
    "PHRASEBOOK": "Sách cụm từ",
    "CONVERSATION_GUIDE": "Hướng dẫn hội thoại",
    "AUDIO_LINGUAL_BOOK": "Sách ngôn ngữ âm thanh",
    "LANGUAGE_EXERCISES": "Bài tập ngôn ngữ",
    "LANGUAGE_COURSEBOOK": "Sách khóa học ngôn ngữ",
    "LANGUAGE_DICTIONARY": "Từ điển ngôn ngữ",
    "CULTURE_GUIDE": "Hướng dẫn văn hóa",
    "LANGUAGE_ATHLETICS": "Sách thể thao ngôn ngữ",
    "PICTURE_BOOKS": "Sách tranh",
    "BOARD_BOOKS": "Sách bìa cứng",
    "EARLY_READERS": "Sách đọc sớm",
    "CHAPTER_BOOKS": "Sách chương",
    "MIDDLE_GRADE": "Sách trung cấp",
    "YOUNG_ADULT": "Sách cho người lớn tuổi",
    "FAIRY_TALES": "Truyện cổ tích",
    "EDUCATIONAL": "Giáo dục",
    "ANIMAL_STORIES": "Truyện về động vật",
    "EASY_READERS": "Sách dễ đọc",
    "HUMOR": "Hài hước",
    "BEDTIME_STORIES": "Truyện trước khi đi ngủ",
    "FABLES": "Truyền thuyết",
    "AUTOBIOGRAPHY": "Tự truyện",
    "MEMOIR": "Hồi ký",
    "BIOGRAPHY": "Tiểu sử",
    "DIARY": "Nhật ký",
    "PERSONAL_NARRATIVE": "Tường thuật cá nhân",
    "AUTOBIOGRAPHICAL_NOVEL": "Tiểu thuyết tự truyện",
    "HISTORICAL_MEMOIR": "Hồi ký lịch sử",
    "CELEBRITY_MEMOIR": "Hồi ký của người nổi tiếng",
    "FICTION": "Tiểu thuyết",
    "NON_FICTION": "Phi hư cấu",
    "MYSTERY": "Trinh thám",
    "THRILLER": "Hồi hộp",
    "FANTASY": "Kỳ ảo",
    "ROMANCE": "Lãng mạn",
    "HISTORICAL": "Lịch sử",
    "POETRY": "Thơ",
    "DRAMA": "Kịch",
    "HORROR": "Kinh dị",
    "SCIENCE_FICTION": "Khoa học viễn tưởng",
    "CONTEMPORARY": "Hiện đại",
    "CLASSICS": "Cổ điển",
    "ADVENTURE": "Phiêu lưu",
    "DYSTOPIAN": "Hậu tận thế",
    "COMICS": "Truyện tranh"
};

const bookTypeTranslations = {
    "FOREIGN": "SÁCH NƯỚC NGOÀI",
    "DOMESTIC": "SÁCH TRONG NƯỚC",
};